---
abstract: upload things to the CPAN
author:
- Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: perl
name: CPAN-Uploader
requires:
  Data::Dumper: '0'
  File::Basename: '0'
  Getopt::Long::Descriptive: '0'
  HTTP::Request::Common: '0'
  HTTP::Status: '0'
  LWP::UserAgent: '0'
  URI: '0'
resources:
  repository: http://github.com/rjbs/cpan-uploader/tree
version: '0.091270'
