---
abstract: 'upload things to the CPAN'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Uploader
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::Long::Descriptive: 0
  HTTP::Request::Common: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Term::ReadKey: 0
  Test::More: 0
resources:
  repository: git://git.codesimply.com/CPAN-Uploader.git
version: 0.100660
