--- 
abstract: upload things to the CPAN
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 0.003
license: perl
name: CPAN-Uploader
requires: 
  File::Basename: 0
  HTTP::Request::Common: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
version: 0.001
